// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Beatmap struct {
	BeatmapID     uuid.UUID
	SongID        uuid.UUID
	Difficulty    string
	Level         string
	InternalLevel pgtype.Numeric
	Type          string
	TotalNotes    int32
	Tap           int32
	Hold          int32
	Slide         int32
	Touch         int32
	Break         int32
	NoteDesigner  string
	MaxDxScore    int32
	IsValid       bool
	UpdatedAt     pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
}

type Score struct {
	ScoreID   uuid.UUID
	BeatmapID uuid.UUID
	SongID    uuid.UUID
	UserID    uuid.UUID
	Accuracy  string
	MaxCombo  int32
	DxScore   int32
	PlayedAt  pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type Song struct {
	SongID      uuid.UUID
	AltKey      string
	Title       string
	Artist      string
	Genre       string
	Bpm         string
	ImageUrl    string
	Version     string
	IsUtage     bool
	IsAvailable bool
	ReleaseDate pgtype.Date
	DeleteDate  pgtype.Date
	UpdatedAt   pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
}

type User struct {
	UserID    uuid.UUID
	SegaID    string
	Password  string
	GameName  string
	TagLine   string
	UpdatedAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type UserDatum struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	GameName        string
	TagLine         string
	Rating          int32
	SeasonPlayCount int32
	TotalPlayCount  int32
	CreatedAt       pgtype.Timestamp
}
