// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Beatmap struct {
	BeatmapID     uuid.UUID
	SongID        uuid.UUID
	Difficulty    string
	Level         string
	InternalLevel pgtype.Numeric
	Type          string
	TotalNotes    int32
	Tap           int32
	Hold          int32
	Slide         int32
	Touch         int32
	Break         int32
	NoteDesigner  pgtype.Text
	MaxDxScore    int32
	IsValid       bool
	UpdatedAt     pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
}

type Score struct {
	ScoreID       uuid.UUID
	BeatmapID     uuid.UUID
	SongID        uuid.UUID
	UserID        uuid.UUID
	Accuracy      string
	MaxCombo      int32
	DxScore       int32
	TapCritical   int32
	TapPerfect    int32
	TapGreat      int32
	TapGood       int32
	TapMiss       int32
	HoldCritical  int32
	HoldPerfect   int32
	HoldGreat     int32
	HoldGood      int32
	HoldMiss      int32
	SlideCritical int32
	SlidePerfect  int32
	SlideGreat    int32
	SlideGood     int32
	SlideMiss     int32
	TouchCritical int32
	TouchPerfect  int32
	TouchGreat    int32
	TouchGood     int32
	TouchMiss     int32
	BreakCritical int32
	BreakPerfect  int32
	BreakGreat    int32
	BreakGood     int32
	BreakMiss     int32
	Fast          int32
	Late          int32
	PlayedAt      pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
}

type Song struct {
	SongID      uuid.UUID
	AltKey      string
	Title       string
	Artist      string
	Genre       string
	Bpm         string
	ImageUrl    string
	Version     string
	IsUtage     bool
	IsAvailable bool
	ReleaseDate pgtype.Date
	DeleteDate  pgtype.Date
	UpdatedAt   pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
}

type User struct {
	UserID       uuid.UUID
	Username     string
	Password     string
	SegaID       string
	SegaPassword string
	GameName     string
	TagLine      string
	UpdatedAt    pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
}

type UserDatum struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	GameName        string
	TagLine         string
	Rating          int32
	SeasonPlayCount int32
	TotalPlayCount  int32
	CreatedAt       pgtype.Timestamp
}

type UserScrapeMetadatum struct {
	UserID       uuid.UUID
	LastPlayedAt pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
}
