services:
  # Go server
  server:
    container_name: maigg-server
    build: .
    ports:
      - ${PORT}:8080
    environment:
      PORT: ${PORT}
      DB_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
        restart: true

  # PostgreSQL
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 30s
      retries: 5
      timeout: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Adminer
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8282:8080 # adminer default uses 8080

volumes:
  pgdata:
