// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
insert into users (
    user_id,
    username,
    password,
    sega_id,
    sega_password,
    game_name,
    tag_line,
    updated_at,
    created_at
)
values ($1, $2, $3, $4, $5, $6, $7, now(), now())
returning user_id, username, password, sega_id, sega_password, game_name, tag_line, updated_at, created_at
`

type CreateUserParams struct {
	UserID       uuid.UUID
	Username     string
	Password     string
	SegaID       string
	SegaPassword string
	GameName     string
	TagLine      string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.Username,
		arg.Password,
		arg.SegaID,
		arg.SegaPassword,
		arg.GameName,
		arg.TagLine,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.SegaID,
		&i.SegaPassword,
		&i.GameName,
		&i.TagLine,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
select
    user_id,
    username,
    password,
    sega_id,
    sega_password,
    game_name,
    tag_line,
    updated_at,
    created_at
from users
order by updated_at desc
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Password,
			&i.SegaID,
			&i.SegaPassword,
			&i.GameName,
			&i.TagLine,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
select
    user_id,
    username,
    password,
    sega_id,
    sega_password,
    game_name,
    tag_line,
    updated_at,
    created_at
from users
where user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.SegaID,
		&i.SegaPassword,
		&i.GameName,
		&i.TagLine,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByMaiID = `-- name: GetUserByMaiID :one
select
    user_id,
    username,
    password,
    sega_id,
    sega_password,
    game_name,
    tag_line,
    updated_at,
    created_at
from users
where game_name = $1 and tag_line = $2
`

type GetUserByMaiIDParams struct {
	GameName string
	TagLine  string
}

func (q *Queries) GetUserByMaiID(ctx context.Context, arg GetUserByMaiIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByMaiID, arg.GameName, arg.TagLine)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.SegaID,
		&i.SegaPassword,
		&i.GameName,
		&i.TagLine,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select
    user_id,
    username,
    password,
    sega_id,
    sega_password,
    game_name,
    tag_line,
    updated_at,
    created_at
from users
where username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.SegaID,
		&i.SegaPassword,
		&i.GameName,
		&i.TagLine,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
update users
set
    username = $2,
    password = $3,
    sega_id = $4,
    sega_password = $5,
    game_name = $6,
    tag_line = $7,
    updated_at = now()
where user_id = $1
returning user_id, username, password, sega_id, sega_password, game_name, tag_line, updated_at, created_at
`

type UpdateUserParams struct {
	UserID       uuid.UUID
	Username     string
	Password     string
	SegaID       string
	SegaPassword string
	GameName     string
	TagLine      string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserID,
		arg.Username,
		arg.Password,
		arg.SegaID,
		arg.SegaPassword,
		arg.GameName,
		arg.TagLine,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.SegaID,
		&i.SegaPassword,
		&i.GameName,
		&i.TagLine,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
