// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_metadata.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserMetadata = `-- name: CreateUserMetadata :one
insert into user_metadata (
    user_id,
    last_played_at,
    updated_at,
    created_at
)
values ($1, $2, now(), now())
returning user_id, last_played_at, updated_at, created_at
`

type CreateUserMetadataParams struct {
	UserID       uuid.UUID        `json:"userID"`
	LastPlayedAt pgtype.Timestamp `json:"lastPlayedAt"`
}

func (q *Queries) CreateUserMetadata(ctx context.Context, arg CreateUserMetadataParams) (UserMetadatum, error) {
	row := q.db.QueryRow(ctx, createUserMetadata, arg.UserID, arg.LastPlayedAt)
	var i UserMetadatum
	err := row.Scan(
		&i.UserID,
		&i.LastPlayedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserMetadataByUserID = `-- name: GetUserMetadataByUserID :one
select
    user_id,
    last_played_at,
    updated_at,
    created_at
from user_metadata
where user_id = $1
`

func (q *Queries) GetUserMetadataByUserID(ctx context.Context, userID uuid.UUID) (UserMetadatum, error) {
	row := q.db.QueryRow(ctx, getUserMetadataByUserID, userID)
	var i UserMetadatum
	err := row.Scan(
		&i.UserID,
		&i.LastPlayedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserMetadata = `-- name: UpdateUserMetadata :one
update user_metadata
set
    last_played_at = $2,
    updated_at = now()
where user_id = $1
returning user_id, last_played_at, updated_at, created_at
`

type UpdateUserMetadataParams struct {
	UserID       uuid.UUID        `json:"userID"`
	LastPlayedAt pgtype.Timestamp `json:"lastPlayedAt"`
}

func (q *Queries) UpdateUserMetadata(ctx context.Context, arg UpdateUserMetadataParams) (UserMetadatum, error) {
	row := q.db.QueryRow(ctx, updateUserMetadata, arg.UserID, arg.LastPlayedAt)
	var i UserMetadatum
	err := row.Scan(
		&i.UserID,
		&i.LastPlayedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
